version: '3.8'
services:
  vprocache01:
    image: memcached
    ports:
      - "11211:11211"
        
  vpromq01:
    image: rabbitmq
    ports:
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest

  vprodb:
    build:
      context: ./Docker-files/db
    image: ardhendushekhar/vprofiledb
    container_name: vprodb
    ports:
      - "3306:3306"
    volumes:
      - vprodbdata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=vprodbpass

  vproapp:
    build: 
      context: ./Docker-files/app
    image: ardhendushekhar/vprofileapp
    container_name: vproapp
    ports:
      - "8080:8080"
    volumes:
      - vproappdata:/usr/local/tomcat/webapps

  vproweb:
    build: 
      context: ./Docker-files/web
    container_name: vproweb
    image: ardhendushekhar/vprofileweb
    ports:
      - "80:80"

volumes:
  vproappdata: {}
  vprodbdata: {}
